/*
 * Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package com.amazon.aace.localNavigation.config;

import com.amazon.aace.core.config.EngineConfiguration;

/**
 * The @c LocalNavigationConfiguration class programmatically generates the "aace.localNavigation"
 * @c com.amazon.aace.core.config.EngineConfiguration used to configure the Local Navigation module.
 */
public class LocalNavigationConfiguration {
    /**
     * Factory method to programmatically generate "aace.localNavigation.localSearch" Engine configuration used for
     * local search features of the Local Navigation module.
     *
     * The data generated by this method is equivalent to providing a JSON configuration file formatted according to
     * the following example:
     * @code{.json}
     * "aace.localNavigation": {
     *    "localSearch": {
     *       "navigationPOISocketPath": "/some/directory/for/sockets/poi_navigation.socket",
     *       "poiEERSocketPath": "/some/directory/for/sockets/poi_eer.socket"
     *    }
     * }
     * @endcode
     *
     * @param navigationPOISocketPath An absolute path where a socket will be created for communication between the
     *        local navigation skill in an LVC process and the local search components of the Auto SDK Engine. Use the
     *        same socket path when configuring LVC.
     * @param poiEERSocketPath An absolute path where a socket will be created for communication between the
     *        offline Alexa service in an LVC process and the local search components of the Auto SDK Engine. Use the
     *        same socket path when configuring LVC.
     */
    public static EngineConfiguration createLocalSearchConfig(
            final String navigationPOISocketPath, final String poiEERSocketPath) {
        return new EngineConfiguration() {
            @Override
            protected long createNativeRef() {
                return createLocalSearchConfigBinder(navigationPOISocketPath, poiEERSocketPath);
            }
        };
    }

    private static native long createLocalSearchConfigBinder(String navigationPOISocketPath, String poiEERSocketPath);
};
