/*
 * Copyright 2017-2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package com.amazon.aace.localSkillService.config;

import com.amazon.aace.core.config.EngineConfiguration;

/**
 * The @c LocalSkillServiceConfiguration class is a factory interface for creating Alexa configuration objects.
 */
public class LocalSkillServiceConfiguration {
    /**
     * Factory method used to programmatically generate Local Skill Service configuration data.
     * The data generated by this method is equivalent to providing the following @c JSON
     * values in a configuration file:
     *
     * @code    {.json}
     * {
     *   "aace.localSkillService":
     *   {
           "lssSocketPath": "<LSS_SOCKET_PATH>",
           "lmbSocketPath": "<LMB_SOCKET_PATH>"
     *   }
     * }
     * @endcode
     *
     * @param [in] lssSocketPath The path for the Unix Domain Socket of the server.
     * @param [in] lmbSocketPath The path for the Unix Domain Socket of the Domain Slot Type AHE server.
     */
    static public EngineConfiguration createLocalSkillServiceConfig( final String lssSocketPath, final String lmbSocketPath )
    {
        return new EngineConfiguration() {
            @Override
            protected long createNativeRef() {
                return createLocalSkillServiceConfigBinder( lssSocketPath, lmbSocketPath );
            }
        };
    }

    // Native Engine JNI methods
    static private native long createLocalSkillServiceConfigBinder( String lssSocketPath, String lmbSocketPath );
};
