/*
 * Copyright 2017-2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

#ifndef AACE_LOCAL_SKILL_SERVICE_LOCAL_SKILL_SERVICE_CONFIGURATION_H
#define AACE_LOCAL_SKILL_SERVICE_LOCAL_SKILL_SERVICE_CONFIGURATION_H

#include "AACE/Core/EngineConfiguration.h"

/** @file */

namespace aace {
namespace localSkillService {
namespace config {

/**
 * The @c LocalSkillServiceConfiguration class is a factory interface for creating Local Skill Service configuration objects.
 */
class LocalSkillServiceConfiguration {
public:
    /**
     * Factory method used to programmatically generate Local Skill Service configuration data.
     * The data generated by this method is equivalent to providing the following @c JSON
     * values in a configuration file:
     *
     * @code{.json}
     * {
     *   "aace.localSkillService":
     *   {
     *     "lssSocketPath": "<LSS_SOCKET_PATH>"
     *     "lmbSocketPath": "<LMB_SOCKET_PATH>"
     *   }
     * }
     * @endcode
     *
     * @param [in] lssSocketPath The path for the Unix Domain Socket of the Local Skill Service HTTP server used by the local skills and skill services to access platform data.
     * @param [in] lmbSocketPath The path for the Unix Domain Socket of the Local Model Builder HTTP server that is used by the Local Skill Service to upload entities used by Local Voice Service for entity resolution of specific slot types.
     */
    static std::shared_ptr<aace::core::config::EngineConfiguration> createLocalSkillServiceConfig( const std::string& lssSocketPath, const std::string& lmbSocketPath = "" );
};

} // aace::localSkillService::config
} // aace::localSkillService
} // aace

#endif // AACE_LOCAL_SKILL_SERVICE_LOCAL_SKILL_SERVICE_CONFIGURATION_H
